name = "fortran-sdl2"
version = "0.5.0"
license = "ISC"
author = "Philipp Engel"
maintainer = "@interkosmos"
copyright = "Copyright (c) 2021, Philipp Engel"
description = "Fortran 2008 ISO C binding interfaces to SDL 2.0"
keywords = ["sdl", "sdl2", "opengl", "glu"]

[library]
source-dir="src"
build-script="Makefile"
